"""add scrape checkpoints

Revision ID: 74d6a77e01c2
Revises: 68167a73faab
Create Date: 2026-02-27 20:52:36.212762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d6a77e01c2'
down_revision = '68167a73faab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('postcode_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['postcode_id'], ['monitored_postcodes.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['monitored_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'postcode_id', 'role_id', name='uq_scrape_checkpoint_combo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_checkpoints')
    # ### end Alembic commands ###
