"""initial schema

Revision ID: 79d6f8a29feb
Revises: 
Create Date: 2026-02-25 19:40:12.569259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d6f8a29feb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('is_agency', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('to_count', sa.Integer(), nullable=False),
    sa.Column('html_size', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitored_postcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('postcode', sa.String(length=16), nullable=False),
    sa.Column('radius_miles', sa.Float(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitored_postcodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_postcodes_postcode'), ['postcode'], unique=False)

    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('jobs_fetched', sa.Integer(), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('monitored_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('postcode_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('search_terms', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['postcode_id'], ['monitored_postcodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adzuna_id', sa.String(length=64), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title_raw', sa.String(length=255), nullable=False),
    sa.Column('title_normalized', sa.String(length=255), nullable=True),
    sa.Column('location_raw', sa.String(length=255), nullable=True),
    sa.Column('location_postcode', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('county', sa.String(length=128), nullable=True),
    sa.Column('monitored_role_id', sa.Integer(), nullable=True),
    sa.Column('is_blue_ribbon', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['monitored_role_id'], ['monitored_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_ads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_ads_adzuna_id'), ['adzuna_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_ads_location_postcode'), ['location_postcode'], unique=False)

    op.create_table('job_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_ad_id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.Column('salary_min_hourly', sa.Float(), nullable=True),
    sa.Column('salary_max_hourly', sa.Float(), nullable=True),
    sa.Column('salary_source', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_ad_id'], ['job_ads.id'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_snapshots')
    with op.batch_alter_table('job_ads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_ads_location_postcode'))
        batch_op.drop_index(batch_op.f('ix_job_ads_adzuna_id'))

    op.drop_table('job_ads')
    op.drop_table('monitored_roles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('scrape_runs')
    with op.batch_alter_table('monitored_postcodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_postcodes_postcode'))

    op.drop_table('monitored_postcodes')
    op.drop_table('email_recipients')
    op.drop_table('email_logs')
    op.drop_table('company_aliases')
    op.drop_table('companies')
    op.drop_table('brands')
    # ### end Alembic commands ###
